### ISSUE TITLE
Workflow edit liveview crashes when selecting 'no credential'.

### ISSUE THREAD

**Issue by stuartc** [OpenFn/lightning#1779] opened 2024-02-20 13:43 UTC
**Describe the bug** A clear and concise description of what the bug is.

When changing the credential to 'nothing' the process crashes.

In production this causes the liveview to reload after a few seconds, probably wiping out other unsaved changes.

**Version number** The version of Lightning you have seen the bug on.

9fbb62c2e1a9c85feee153058f1b418392ed2072

I have reproduced this locally on main:

- [x] Yes
- [ ] No

**To Reproduce** Steps to reproduce the behavior:

1. Go to any existing workflow
2. Select a job
3. Change the adaptor (likely anything other than the credential will do the same)
4. Click the credential select box, assuming it was already 'blank', select the blank option again.
5. Trigger some kind of push patch, like click to open the inspector.

Check your logs and see something like:

```
[error] GenServer #PID<0.1602.0> terminating
** (Ecto.Query.CastError) deps/ecto/lib/ecto/association.ex:760: value `""` cannot be dumped to type :binary_id in query:

from c0 in Lightning.Credentials.Credential,
  join: p1 in Lightning.Projects.ProjectCredential,
  on: p1.credential_id == c0.id and p1.id == ^"",
  select: c0
```

**Expected behavior** A clear and concise description of what you expected to
happen.

`""` should be treated as null, and we shouldn't be checking for ownership of `null`.

**Screenshots** If applicable, add screenshots to help explain your problem.

https://github.com/OpenFn/lightning/assets/144796/907cf2bd-c547-4f0f-8bdd-f9d84069568c

**Comment by christad92** [comment] 2024-02-23 14:41
Hi @stuartc there is some bit of challenge replicating this bug. Can you try it again to confirm if this is still happening?

**Comment by jyeshe** [comment] 2024-05-15 16:07
> Hi @stuartc there is some bit of challenge replicating this bug. Can you try it again to confirm if this is still happening?
Also couldn't replicate on Lightning opening the inspector with this change:
![image](https://github.com/OpenFn/lightning/assets/44991200/b2d805a7-6233-4a1e-bd9d-a9ff56529d81)

**Comment by jyeshe** [comment] 2024-05-15 18:39
Couldn't reproduce anymore on Thunderbolt but the way I did before was a hint to enable more workflows than the subscription is allowed to:
![image](https://github.com/OpenFn/lightning/assets/44991200/224451b3-4344-47c0-89d9-b05cfe54834c)

Steps:
1. `mix do ecto.reset, initial.setup, demo.seeds`
2. `iex -S mix phx.server`
3. Login with `demo@openfn.org`
4. Disable OpenHIE workflow trigger
5. Create another workflow and save it
6. Got back to OpenHIE and enabled it
7. Create a run and save (the workflow is saved).

**Comment by jyeshe** [comment] 2024-05-15 18:43
![image](https://github.com/OpenFn/lightning/assets/44991200/78b919b5-ccec-496e-a497-da6659b1a8f9)

**Comment by christad92** [comment] 2024-05-15 18:49
Thanks @jyesh. From the timestamp, this bug was reported before introduced limits so I'm not sure they are related. Regardless, if we can't replicate this, we should close the issue and be in a look out for it.

**Comment by jyeshe** [comment] 2024-05-15 19:05
First time I got this kind of error was on the scenario of the issue: https://github.com/OpenFn/thunderbolt/issues/99#issuecomment-2084547164

**Comment by christad92** [comment] 2024-05-15 20:04
Got it. I was able to replicate thunderbolt/99 and they _may_ be related. 

So the issue is that unsaved changes are not persisted when live view refreshes.

**Comment by christad92** [comment] 2024-05-15 20:06
This might be related to #2007 if it's a mount/refresh related issue.

**Comment by christad92** [comment] 2024-05-16 08:26
Couldn't replicate the bug. We'll be on the lookout

**Closed by christad92** 2024-05-16 08:26 UTC
Labels: bug
