### ISSUE TITLE
Don't run inactive workflows when webhook requests are received

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#469] opened 2022-11-29 07:17 UTC
**Describe the bug** A clear and concise description of what the bug is.
When I make a post request to the webhook URL of a `disabled` trigger, the job is still run and I get a 200 response. 

**To Reproduce** Steps to reproduce the behavior:

1. Go to workflows
2. Create a job with a webhook trigger and set it to disabled. 
3. Make a post request to that webhook URL
4. See 200 response and the job gets run and appears in the runs history

**Expected behavior** A clear and concise description of what you expected to
happen.
If a trigger is disabled, I would it to not run. I would expect to get a different error code (@taylor I think [403](https://www.rfc-editor.org/rfc/rfc7231#section-6.5.3) would be the right code and an API response that says "Unable to process request, trigger is disabled. Enable it on OpenFn to allow requests to this endpoint."

**Screenshots** If applicable, add screenshots to help explain your problem.

[Uploading... Screen Recording 2022-12-16 at 18.33.05.mov]
**Additional context** Add any other context about the problem here.

**Comment by taylordowns2000** [comment] 2022-12-07 12:56
@amberrignell , i can't reproduce this and don't see a ton of details above. mind if i close it?

**Closed** 2022-12-29 20:04 UTC
Labels: bug
