### ISSUE TITLE
Workflow diagram breaks if a workflow contains an invalid adaptor name

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#1034] opened 2023-08-17 15:56 UTC
There is a util function in `assets/js/workflow-diagram/util/get-adaptor-name` which expects a string specifier of the form `@openfn/language-comon`.

It's a bit too rigid about this and if an adaptor name does not match that pattern, it'll throw and the workflow diagram will blow up.

**Comment by josephjclark** [comment] 2023-08-17 15:58
I think this is the fix:
```
export default specifier => {
  if (specifier) {
    const  result = specifier.match(/@openfn.language-(.+)@/);
   if (result && result.length === 2) {
      const [prefix, name] = result;
      return name || 'unknown';
   }
  }
  return '';
};
```

**Comment by mtuchi** [comment] 2023-11-16 08:03
Closing since we can not reproduce this bug

**Closed by mtuchi** 2023-11-16 08:03 UTC
Labels: bug
