### ISSUE TITLE
Project deletion feels broken

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2633] opened 2024-11-05 13:25 UTC
1. When attempting to delete a project (with activity) before the scheduled deletion date, the user is blocked until the deletion is successful or something breaks. We would want a process where the deletion can be done in the background. In this case, if there is an error, we should alert the user that the deletion failed. 
2. Project deletion job is timing out.

**Comment by midigofrank** [comment] 2024-11-11 05:14
Related to #2632

**Comment by midigofrank** [comment] 2024-11-12 08:36
Duplicate of #2632

**Closed by midigofrank** 2024-11-12 08:36 UTC
