### ISSUE TITLE
Create generic module which creates audit events

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#44] opened 2022-03-28 07:26 UTC
- [https://luizdamim.com/blog/tracking-changes-with-context-using-phoenix-and-ecto/](https://luizdamim.com/blog/tracking-changes-with-context-using-phoenix-and-ecto/)

**Comment by taylordowns2000** [comment] 2023-09-16 22:45
duplicate of #271

**Closed by taylordowns2000** 2023-09-16 22:45 UTC
