### ISSUE TITLE
Workflow Diagram: Placeholder icons sometimes don't appear

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/Lightning#846] opened 2023-05-18 08:48 UTC
Sometimes the two icons in the screenshot below fail to render:

![image](https://github.com/OpenFn/Lightning/assets/7052509/f2a36041-c2c3-4af3-a191-8f057cf6a6cb)

Other SVG icons - including React heroicons in the editor - work fine.

SVGs are in the DOM, with stroke and a path. It looks like they're being rendered with zero width.

We've only see this on Amber's Mac (it's fine on Mtuchi's mac)

I cannot reporoduce on my machine.

We're calling this low priority for now because it doesn't actually block any behaviour.

**Comment by taylordowns2000** [comment] 2023-09-29 07:10
I haven't been able to reproduce this and haven't seen it since the report. Closing for now @NickOpenFn , but please feel free to re-open if it pops up!

**Closed by taylordowns2000** 2023-09-29 07:10 UTC
Labels: bug
