### ISSUE TITLE
Filter runs by date

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#242] opened 2022-08-10 15:14 UTC
### User story 
As a user that is searching for a run that happened at a particular point in time (or looking to reprocess a set of requests that happened between 2 specific dates), I would like to be able to filter workflow runs by date (before/after/between). 

### Implementation notes

**Comment by taylordowns2000** [comment] 2022-08-28 08:21
Duplicate of #285

**Closed by taylordowns2000** 2022-08-28 08:21 UTC
Labels: needs more detail
