### ISSUE TITLE
Store log lines in a separate table

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#197] opened 2022-07-20 09:56 UTC
In order to deal with the future design of process based workers, and the asynchronous nature they have. It will be beneficial to store log lines as rows in a table.

A job/worker will be able to emit a log line (\n terminated or EOL) along with it's us (microsecond) integer timestamp.

This way, no matter which instance receives the log line, they can be queried in order.

**Comment by josephjclark** [comment] 2023-02-21 11:31
Closing as duplicate of #514

**Closed by josephjclark** 2023-02-21 11:31 UTC
