### ISSUE TITLE
Critical: Creating a new job doesn't open the job panel

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1538] opened 2023-12-07 09:02 UTC

**Comment by NickOpenFn** [comment] 2023-12-07 09:46
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1538?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by elias-ba** [comment] 2023-12-07 23:45
@NickOpenFn I am moving this to blocked, I couldn't reproduce the bug locally. Can you please add clear steps on how to reproduce it or help me do so ?

**Closed** 2023-12-18 18:24 UTC
Labels: bug
